# Generated by Django 6.1.1 on 2026-09-25 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_text', models.TextField()),
                ('topic', models.TextField(blank=True, default='')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('paragraph_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('criterion_1', models.FloatField(default=0)),
                ('criterion_2', models.FloatField(default=0)),
                ('criterion_3', models.FloatField(default=0)),
                ('criterion_4', models.FloatField(default=0)),
                ('criterion_5', models.FloatField(default=0)),
                ('criterion_6', models.FloatField(default=0)),
                ('criterion_7', models.FloatField(default=0)),
                ('criterion_8', models.FloatField(default=0)),
                ('criterion_9', models.FloatField(default=0)),
                ('criterion_10', models.FloatField(default=0)),
                ('criterion_11', models.FloatField(default=0)),
                ('criterion_12', models.FloatField(default=0)),
                ('ai_review', models.TextField(blank=True, default='')),
                ('errors', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
