# Generated by Django 6.1.1 on 2026-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='criterion_10_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_11_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_12_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_1_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_2_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_3_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_4_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_5_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_6_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_7_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_8_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='essay',
            name='criterion_9_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
