# Generated by Django 6.1.1 on 2026-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_essay_criterion_10_reason_essay_criterion_11_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
